# This file is generated by scripts/database.sh.
# Please do not manually edit this file.

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    String,
    Text,
    text,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()
metadata = Base.metadata


class DieselSchemaMigrationTable(Base):
    __tablename__ = "__diesel_schema_migrations"

    version = Column(String(50), primary_key=True)
    run_on = Column(
        DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )


class PersonTable(Base):
    __tablename__ = "person"

    id = Column(BigInteger, primary_key=True)
    name = Column(Text, nullable=False)
    email = Column(Text, nullable=False, unique=True)
    password = Column(Text, nullable=False)
    public_key = Column(Text, nullable=False)
    secret = Column(Text, nullable=False)
    verified = Column(Boolean, nullable=False)
    updated_at = Column(DateTime, nullable=False)


class DeviceTable(Base):
    __tablename__ = "device"

    id = Column(BigInteger, primary_key=True)
    person = Column(ForeignKey("person.id"), nullable=False)
    name = Column(Text, nullable=False)
    ip_address = Column(Text, nullable=False)
    location = Column(Text, nullable=False)
    token_iat = Column(BigInteger, nullable=False)
    last_login = Column(DateTime, nullable=False)

    person1 = relationship("Person")


class FolderTable(Base):
    __tablename__ = "folder"

    id = Column(BigInteger, primary_key=True)
    person = Column(ForeignKey("person.id"), nullable=False)
    name = Column(Text, nullable=False)
    sharing = Column(Boolean, nullable=False)
    built_in = Column(Boolean, nullable=False)

    person1 = relationship("Person")


class AccountTable(Base):
    __tablename__ = "account"

    id = Column(BigInteger, primary_key=True)
    person = Column(ForeignKey("person.id"), nullable=False)
    folder = Column(ForeignKey("folder.id"), nullable=False)
    name = Column(Text, nullable=False)
    username = Column(Text, nullable=False)
    password = Column(Text, nullable=False)
    note = Column(Text, nullable=False)

    folder1 = relationship("Folder")
    person1 = relationship("Person")


class ShareTable(Base):
    __tablename__ = "share"

    folder = Column(ForeignKey("folder.id"), primary_key=True, nullable=False)
    person = Column(ForeignKey("person.id"), primary_key=True, nullable=False)
    owner = Column(Boolean, nullable=False)
    view_only = Column(Boolean, nullable=False)
    secret = Column(Text, nullable=False)
    confirmed = Column(Boolean, nullable=False)
    created_at = Column(DateTime, nullable=False)

    folder1 = relationship("Folder")
    person1 = relationship("Person")
